### ISSUE TITLE
Stuck on "We're loading thumbnails..."

### ISSUE THREAD

**Issue by jakeyem** [oodesign/merge-duplicate-symbols#106]
When attempting to merge 2 selected symbols, Merge Duplicate window gets stuck on "We're loading thumbnails..."

I can't use my shiny new plug-in I just bought :(

Running macOS 10.15.6
Sketch 68.2

**Comment by oodesign** [comment]
Hi @jakeyem,

Sorry to hear that :(
I'm afraid we cannot reproduce the issue you describe with our testing set, though. 

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by elvintsang** [comment]
Hi @oodesign I'm also seeing the same thing. I've just emailed you my log file – hope you can help!

**Comment by oodesign** [comment]
Hi @elvintsang ,

Thanks for sending us those logs. It helps a lot! 🥰

We're aware of this issue, and currently working on a fix.

We've identified this issue on Sketch files that use tint overrides. May it be your case?
The exact pattern for the issue is:


- Having symbols with **Tints** defined. Let's say this is **SymbolA**.
- Having other symbols that had the initial symbol inside of them (symbol nesting). So that would be **SymbolB containing SymbolA**.
- In SymbolB, there was a **group containing SymbolA** (let's call it TintGroup), and the group **also had a tint defined** on it.
- In any artboard, SymbolB was used, and there was a **tint override set for the TintGroup** group.

Does any of that sound familiar to you? 

Thanks for your help!

**Comment by elvintsang** [comment]
Hi @oodesign thanks for your reply. I have used tints and tint overrides in the file – I don't think I have applied any tints to groups though, just symbol instances. Incidentally the symbols I was trying to merge don't have any tints. Would you like a copy of my sketch file to look in more detail?

**Comment by oodesign** [comment]
Hi @elvintsang ,

That would be awesome, thank you! We'd be happy to investigate a bit further the issue.
You can [send us a mail](mailto:oscar@oodesign.me) , or use the sharing platform you feel the most comfortable with. Just let us know how to get it :) .

**Comment by oodesign** [comment]
Hi @elvintsang ,

We got the file, and can reproduce the issue you describe with it.
We'll take some time to investigate it further, and come back to you when we have an answer.

Thanks a lot for your help!

**Comment by jpawlowicz** [comment]
+1 
Unfortunately I'm experiencing the same issue for a long time now, I can't get it to work. 
I don't have any tints, I'm trying to merge 2 identical buttons with 2 layers, one for color (which has a layer style, not a tint) and a text on it. It's not grouped, no tints, just 2 layers and even then 'loading thumbnails' is the only thing I see. 

I have a huge project with a lot of symbols and while working on it I also need to clean it up and we have bought the plugin to help with that, looking forward to hear about resolved issue because it's just frustrating...

**Comment by oodesign** [comment]
Hi @jpawlowicz ,

We're actively working on a fix for that. We're currently in testing stage, so hope to release it soon :)
I'll be happy to let you know when it's out there.

Thanks!

**Comment by oodesign** [comment]
Hi @jpawlowicz @elvintsang @jakeyem ,

We just release v6.5.0, which will hopefully solve this issue.
May you please check it out and let us know how it worked for you?

Thanks!

**Comment by jpawlowicz** [comment]
@oodesign hello! I have just updated it and it worked for the first time in a long time, even searching for symbols with the same names works (I think for the first time since June / July for me). Thank you so much!

**Comment by oodesign** [comment]
Glad it worked for you @jpawlowicz ! 😊
