### ISSUE TITLE
Merge symbols with the same not working.

### ISSUE THREAD

**Issue by fatimanu** [oodesign/merge-duplicate-symbols#109]
Hi
I've just purchased and tried the plugin.
"Replace selected symbols" works great. But when I click "replace symbols with the same name" nothing happens.

We are building an atomic design system, where I'm the gate keeper. 
All the other designers work on their cloud file and once a component is ready I copy them from their files to our core library.

Problem is, some of this components have symbols that are ready taken from the core library, so when I copy those components, sketch creates a duplicated symbol.

So I get stuck having lots of duplicated (and of course, exact same name) symbols. Selecting and replacing is working better than no plugin at all, but replace all symbols with the same name is exactly what I needed and expected.

I'm running in the latest sketch version (v69).

Thank you so much!

**Comment by oodesign** [comment]
Hi @fatimanu ,

Sorry to hear that :(
I'm afraid we cannot reproduce the issue you describe with our testing set, though. 

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment]
Hi @fatimanu ,

Are you still experiencing this issue?

Thanks!
