### ISSUE TITLE
Merge layer styles (from list) don't work

### ISSUE THREAD

**Issue by devcofa** [oodesign/merge-duplicate-symbols#112]
Hello!

Thanks for the Merge Duplicates plugin, it helps me a lot!

But one of my most used features don't work anymore, tried launch from menu and hotkey. The screen with the styles list doesn't show up.

Sketch Version 69 (107357)

Thanks.

**Comment by oodesign** [comment]
Hi @devcofa ,

Sorry to hear that :(

May I ask you which plugin version are you using?

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by devcofa** [comment]
I've sent logs to the email you provided, but there is a 5.6.0 version in logs otherwise in Sketch it's 6.5.1
<img width="499" alt="Screenshot 2020-10-20 at 16 32 13" src="https://user-images.githubusercontent.com/51321192/96593313-06c6a780-12f2-11eb-86f4-984e9dc7a77a.png">

**Comment by devcofa** [comment]
Also, I had to say the plugin works longer than usual on all operations (much longer)

**Comment by devcofa** [comment]
Merge selected symbols isn't working too =(

**Comment by oodesign** [comment]
Hi @devcofa ,

We just released v6.5.2, that may hopefully fix this issue.
May you please give it a try and let us know how it worked for you?

Thanks!

**Comment by devcofa** [comment]
Hi!

Yes, the features work now, but it still takes a lot of time. I’m not sure how I can help to determine what it may cause.

Anyway thank you!

**Comment by oodesign** [comment]
We're actively working on improving the overall plugin performance. 
I'll be happy to let you know when we release a version related with it.

Thanks a lot!

**Comment by devcofa** [comment]
Thank you so much!

**Comment by devcofa** [comment]
Hello!

I’ve recently contacted Sketch due to the performance of Sketch 69+ overall, and the Sketch team said that they have significant troubles with performance since Sketch 69 and actively working on a fix. Maybe my plugin performance troubles don’t due to the plugin but to Sketch. I just want to let you know.

Thank you!

**Comment by oodesign** [comment]
Thanks for sharing with us.
Hopefully we'll both improve performance and you'll be able to merge symbols and styles in a breeze 😊
