### ISSUE TITLE
Merge Symbol not working

### ISSUE THREAD

**Issue by helenededieu** [oodesign/merge-duplicate-symbols#120]
Hi,
Since two days when I launch merge duplicate > symbols > merge duplicates with the same name nothing happen, the spinning wheel appears for a bit, and thats all, the merge symbol window doesn't open.
The plugin is enable in my preferences, so I am not sure where it come from.
Thanks.

**Comment by oodesign** [comment]
Hi @helenededieu ,

Sorry to hear that :(

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment]
Hi @helenededieu ,

Are you still experiencing this issue?

Thanks!

**Comment by helenededieu** [comment]
Hi Oscar,

So sorry I didn’t update you on this.
Installing the new plugin solved the problem, thanks.
It is just a bit slower than before, but I guess it’s because there is more than 700 symbols 😊

Thanks for your help !

Hélène Dedieu

Senior Visual Designer
[signature_153162916]
20 Farringdon Road ‑ London EC1M 3HE
www.karmarama.com<https://www.karmarama.com/>

This email may be confidential or privileged. If you have received this communication by mistake please don't be daft and forward it on to anyone else. The right thing to do is erase all copies and attachments and then ping me back to say it went to the wrong person. Thanks.

**Comment by oodesign** [comment]
Hi @helenededieu ,

Glad it worked fine for you! 😊
