### ISSUE TITLE
Possible merge duplicate plugin conflict?

### ISSUE THREAD

**Issue by Bequiagal** [oodesign/merge-duplicate-symbols#122]
I am finding that a simple "Merge duplicate selected symbols" won't fully run unless i turn off all InVision plugins. (New DSM and Craft Manager) 

With the InVision plugins active, the Merge Duplicate panel will show up but never populate with the selected symbols so i can choose what to merge. 

After turning off BOTH InVision DSM and InVision Craft Manager, Merge Duplicates works fine. 

Active plugins: Abstract, Merge Duplicates and Sync with Library. 
Sketch: 69.2
Mac OS: 10.15.7

**Comment by oodesign** [comment]
Hi @Bequiagal ,

I'm afraid we are not able to reproduce the issue with DSM and Craft 😔. 
We actually use both regularly, and haven't seen so far any clue that they may interfere with Merge Duplicates. 🤔
 
May you please send us your plugin logs?

I guess you're already familiar with logs by now 😅, but just in case:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by Bequiagal** [comment]
I am not experiencing this today... The scenario hasn't changed though- same plugins activated, same file, same operation. 

I am not going to send a log as it appears to be working or an intermittent issue.

**Comment by oodesign** [comment]
Absolutely, no worries.

Please let us know if it happens on a regular basis or if you manage to find a way to reproduce it.

Thank you!
