### ISSUE TITLE
Merging Layers causes layer styles to become ghost styles

### ISSUE THREAD

**Issue by Sjennon** [oodesign/merge-duplicate-symbols#123]
Hi! I am currently trying to manage a design system and I am getting a major blocker.

I had to update the color library and remove all layer styles we're not using anymore. Therefore I merged a bunch of (duplicated) layer styles. In my color library file only the layer styles that I want are still there.

However, inside my working files there are some ghost styles. This means that when I click on a component/symbol with such layer style, it appears like the old layer style, but it's separate.

I am unable to manage/reuse/delete these styles and they do not appear in the document layer styles either.

![image](https://user-images.githubusercontent.com/6576878/98095616-18c84e80-1e8b-11eb-9f47-5b61284a54b1.png)

Is there a way to fix this?

**Comment by oodesign** [comment]
Hi @Sjennon ,

I'm afraid Merge Duplicates action scope is restricted to the current open document, and therefore all "child" documents (files using library symbols or styles you are merging in the library file) won't get automatically updated. 

If you need to "update" the child documents, I'd suggest to use "Merge duplicate layer/text styles (from list)" option to "map" the discarded/deprecated styles (what you refer as "ghost styles", that Sketch keeps and that are still applied to the child document's layers/texts) to the ones you'd like to keep.

That said, we also see the huge value of being able to update the library and update all related child files accordingly. I'll be happy to let you know if at some point we're able to bypass that restriction and add that feature to Merge Duplicates.

**Comment by Sjennon** [comment]
Hi @oodesign, thank you for your response!

Does that mean I need to 'remap' the colors for all the child documents manually?

I'd be great to have this affect all the child documents as I'm using a pretty large design system which is applied in over 50+ child documents 😅

**Comment by oodesign** [comment]
Hi @Sjennon ,

Yes, I'm afraid that may require a ton of manual (boring) work... 😔 .

A while back there was no option for plugins to affect other files (per Sketch restriction). 
We currently may have an open door when dealing with actually open documents. However, the approach is still pretty fragile (as when working with version control tools, like Abstract, unless you have all files - including libraries - in the same project, there would be no way to even open the different files in a tracked way, so that all the changes would be done and stored properly).

We'll keep investigating ways to workaround it. Meanwhile, I guess "Merge from list" is our best guess to reduce the amount of work...
