### ISSUE TITLE
Text Layer Merging crashes

### ISSUE THREAD

**Issue by nabilghulam** [oodesign/merge-duplicate-symbols#124]
Hey, any idea why the merge text layers is crashing?
Never got it to work.

**Comment by oodesign** [comment]
Hi @nabilghulam,

Sorry to hear it's not working fine for you... 😔. 

I'm afraid we cannot reproduce the issue you describe with our testing set, though. 

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and reopen the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment]
Hi @nabilghulam ,

Are you still experiencing this issue?

Thanks!
