### ISSUE TITLE
Too many updates

### ISSUE THREAD

**Issue by michelluarasi** [oodesign/merge-duplicate-symbols#128]
Hi

You're updating the plugin way to often. It's so annoying that i'm considering to uninstall and install when needed. Would it be possible for you to bundle minor tweaks and fixes in the future and just push critical things directly?

Thanks for consideration.

Best
Michel

**Comment by oodesign** [comment]
Hi @michelluarasi ,

Actually it's a very fair point. I'm sorry we're bothering you with so many updates. 

We do have a very specific release plan for all major and minor releases (first two numbers of the version, like 8.0.0, 8.1.0, 8.2.0, ...), and we really try to bundle as much as we can in those. You shouldn't see many of those.

All patch versions (the third number of the version, like 8.0.1, 8.0.2, 8.0.3, ...) are releases including fixes (that solve a very specific issue each), or updates tied to Sketch updates. These are published as quickly as possible, because the related issues are blocking/ preventing designers to actually use the plugin, or would cause Merge Duplicates to stop working with newer versions of Sketch. 

That said, we'll try our best to keep updates to the minimum 😊

Thanks a lot for your feedback!

**Comment by michelluarasi** [comment]
Thanks a lot!
