### ISSUE TITLE
Merge symbols with the same name not working.

### ISSUE THREAD

**Issue by fatimanu** [oodesign/merge-duplicate-symbols#129]
Hi,

Sorry for the very late response.
I'm opening this thread again, since I wasn't able to answer you and I'm still experiencing the issue.
This is what I wrote in the previous thread:

"When I click "replace symbols with the same name" nothing happens.
We are building an atomic design system, where I'm the gate keeper.
All the other designers work on their cloud file and once a component is ready I copy them from their files to our core library.

Problem is, some of this components have symbols that are ready taken from the core library, so when I copy those components, sketch creates a duplicated symbol.

So I get stuck having lots of duplicated (and of course, exact same name) symbols. Selecting and replacing is working better than no plugin at all, but replace all symbols with the same name is exactly what I needed and expected."

I'm running in the latest sketch version (69.2).
The requested Log is attached so you can check what the issue might be.
[Plugin Log.log](https://github.com/oodesign/merge-duplicate-symbols/files/5541985/Plugin.Log.log)

Thank you so much!

**Comment by oodesign** [comment]
Hi @fatimanu ,

Thanks for the detail, and for sending us the logs!

Per your plugin log info, Merge Duplicates seems to have issues accessing a linked library. 
It shouldn't be an issue (as we believe we handle it properly), but may I ask... does your project have symbols/styles coming from an external library that is not available anymore?

Also, I'm afraid it's an issue that we cannot reproduce on our side... 
May I ask you to please [send us](mailto:oscar@oodesign.me) your design file (and related libraries) so that we can investigate it further?

Your files are and will remain confidential. We ensure they will only be used to investigate the issue you're describing, deleted after closing it, and never stored or used for any other means.

Also please feel free to use the sharing platform you prefer to send us the files, if you don't want to send them via email. Just [let us know](mailto:oscar@oodesign.me) the details to get them.

Thank you!

**Comment by fatimanu** [comment]
Hey,

Thank you for your response.
I just answered you in private.

thanks!

**Comment by fatimanu** [comment]
Hi!
Any answer about the issue I'm having with the plugin?
I've sent you my design files.

Let me know if you need anything else for solving this issue.

thanks.

**Comment by oodesign** [comment]
Hi @fatimanu ,

I'm afraid we didn't get your private message (via mail, I guess?).
May you please send it back to us?

Thanks!

**Comment by fatimanu** [comment]
Hi,

Yes,sent it to the email that was on the link you mentioned above.
I'm forwarding the email again now.
Please check your spam folder.

thanks!

**Comment by fatimanu** [comment]
Hi,

Thank you very much for your assistance and kindness.
Issue solved.

**Comment by oodesign** [comment]
Just as a foot note to keep track:

In this case the issue seemed to be solved by uninstalling and installing again the Merge Duplicates plugin (which shouldn't have made a difference, but it actually did 😅).

Please, let us know if you have any further issues with it.

Thanks!
