### ISSUE TITLE
Merge Duplicates takes a very long time to actually go through elements.

### ISSUE THREAD

**Issue by andrewdaniels** [oodesign/merge-duplicate-symbols#131]
The last 8+ versions have been incredibly slow. I mean it has rendered the entire tool useless in my workflow. It takes forever to load the different options that I can merge. The time usually takes longest when switching between the options on the left, but even after switching the options on the left it takes sometimes up to 4 minutes to close out the changes and allow me to use Sketch again. This is incredibly time consuming... I used to use merge duplicates 3-4 times a day; because it was a very useful tool -- I work in a team where we share documents and all the designers make the documents messy. My job is clean up those documents.

This tool used to help me clean up and consolidate the files together. But recently it hasn't been any help whatsoever. Video attached below.

https://www.dropbox.com/s/4e3aqd2nco4egrx/Screen%20Recording%202020-10-27%20at%2010.48.51%20AM.mov?dl=0

**Comment by oodesign** [comment]
Hi @andrewdaniels ,

We've identified several performance issues (most of them related with dealing with big files) since we moved the plugin to use the official Sketch API (which we needed to keep up with the most recent Sketch changes, like tint overrides, and color variables). 

We're putting all of our effort (and working with Sketch) on fixing them, and hope to get Merge Duplicates as efficient as it used to be as soon as possible. This is our primary focus currently.

We sincerely apologize for all the issues this may be causing. 
I'll make sure to keep you updated on it.

P.S. Merge Duplicates was moved to use the official API on v6.5.0. If you don't need to deal with tint overrides and color variables (and while we find a better performant solution) you may want to give **v6.4.3** a try. You can always get older versions on https://github.com/oodesign/merge-duplicate-symbols/releases .

**Comment by andrewdaniels** [comment]
Thank you so much! I'll install that version for now. Thanks for working on it, love the tool; just love it when it works and improves my workflow -- Ik software can be difficult especially when trying to work within a tools' framework. Thanks again.

**Comment by oodesign** [comment]
Hi @andrewdaniels ,

We just released v8.1.0, that should be way faster processing symbols than the previous versions.
May you give it a try and let us know how it worked for you?

Thanks!

**Comment by andrewdaniels** [comment]
Hey thanks so much!! It does allow super quick viewing and selecting of the duplicates. I was able to view and select very easy which was so nice... I tried it two times today both times after I clicked "Merge Duplicates" it froze sketch and then crashed sketch! Just some more things to work no =) thanks for improving and working on it!


<img width="1408" alt="Screen Shot 2020-12-02 at 9 53 03 AM" src="https://user-images.githubusercontent.com/6546335/100944938-e16ab300-34c5-11eb-844b-50bae336f253.png">

**Comment by oodesign** [comment]
Hi @andrewdaniels ,

For now we have "just" boosted the **Merge symbols** features. Layer & text styles may still be slow (for now). Good news is that... we're already applying the same improvements to style processing, so... watch this space! 😊

**Comment by oodesign** [comment]
Hi @andrewdaniels ,

We just released v8.2.0, which should be way way faster processing layer and text styles.
May you please give it a try and let us know hoe it worked for you?

Thanks! 🥰

**Comment by andrewdaniels** [comment]
I will do that! Thank you! My other designer will be thrilled to hear this! He just downgraded to 6.5.0 so he could run the other ones for a project! This is perfect timing thank you again!

Respectfully,
Andrew Daniels
Head of Product Design & Business Development
Kaleo Design
Cell: (210) 405-5108
