### ISSUE TITLE
Merge Duplicates stuck on "We're loading thumbnails..."

### ISSUE THREAD

**Issue by jakeyem** [oodesign/merge-duplicate-symbols#135]
I have been having this issue for a while now. I've been seeing this is both cloud and non-cloud sketch files, with libraries active, and inactive. Even with Merge Selected Symbols. I have even left the plug-in running overnight and it was still stuck. 

<img width="1012" alt="Screen Shot 2021-01-04 at 2 27 37 PM" src="https://user-images.githubusercontent.com/72154026/103585981-01acd980-4e99-11eb-8133-03c9d1252fd7.png">

**Comment by oodesign** [comment]
Hi @jakeyem ,

Merge selected symbols shouldn't take long time to load, so it seems like a bug on our side.

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and reopen the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by jakeyem** [comment]
@oodesign Log sent!

**Comment by oodesign** [comment]
Got it, thanks!

We'll take a deep look and come back to you asap. :)

**Comment by oodesign** [comment]
Hi @jakeyem ,

In order to investigate further the issue, may I ask you to please [send us](mailto:oscar@oodesign.me) your design file (and related libraries)?

Your files are and will remain confidential. We ensure they will only be used to investigate the issue you're describing, deleted after closing it, and never stored or used for any other means.

Also please feel free to use the sharing platform you prefer to send us the files, if you don't want to send them via email. Just [let us know](mailto:oscar@oodesign.me) the details to get them.

Thanks a lot!

**Comment by oodesign** [comment]
Hi @jakeyem,

Are you still experiencing issues with Merge Duplicates? Is there anything we can help with?

**Comment by jakeyem** [comment]
@oodesign I wasn't able to get you the NDA to share the file with you. 

No change in behavior after today's update.

**Comment by oodesign** [comment]
Hi @jakeyem ,

We've just released v8.2.2, which addresses an issue happening when accessing overrides with tints, and that may be related to the issue you describe.

May you please give it a try and let us know how it worked for you?

Thanks!
