### ISSUE TITLE
license issue on the new computer

### ISSUE THREAD

**Issue by saydamzulal** [oodesign/merge-duplicate-symbols#137]
The plugin was working great for the case of merging symbols and elements. But I had to change my computer and I wasn't able to sign out for my account. Now running the plugin on my new computer, an error message shows up on the screen. It would be great there was a way of using it again with the same license number. 
<img width="616" alt="Screen Shot 2021-01-14 at 11 27 11" src="https://user-images.githubusercontent.com/77433781/104564019-77fcc900-565b-11eb-9616-07286a5e3b98.png">

**Comment by oodesign** [comment]
Hi @saydamzulal ,

We're trying to keep this space for technical-related issues. 😊

For anything related with licensing, may I ask you to please [send us an email](mailto:oscar@oodesign.me) with your purchase details (email account used for the purchase, and license key), so that we can continue the conversation from there?

Thank you!

**Comment by saydamzulal** [comment]
Hi @oodesign ,

I thought it was a technical problem that I couldn't log out for my license. I will send an e-mail with my purchase details.
 
Thanks for your help!
