### ISSUE TITLE
The plugin crashes and closes Sketch

### ISSUE THREAD

**Issue by vegadesign** [oodesign/merge-duplicate-symbols#138]
When I click any action in the plug-in (v8.2.0), it crashes and the Sketch closes. The operation system is BigSur 11.1 (20C69) and the MacBook Pro on M1 chip. The log file cannot be sent, I can't open the Settings to enable it, the Sketch always closes

**Comment by oodesign** [comment]
Hi @vegadesign ,

May you please unzip and copy the attached file ("merge.json") in your Sketch plugins folder, and try to run the plugin again? This should help enable the logs.

You may find the Sketch Plugins folder at /Users/<your_username>/Library/Application Support/com.bohemiancoding.sketch3/Plugins. 
You may also get there by using the Sketch menu "Plugins > Manage plugins... > ⚙️ > Reveal plugins folder" and opening the "Plugins" folder.

Once you've copied it:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with.
3. Run the Merge Duplicates command you were having issues with (Settings, in this case, but can try afterwards with Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants).
4. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and relaunch the app).
5. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

[Merge.zip](https://github.com/oodesign/merge-duplicate-symbols/files/5830246/md.zip)

**Comment by vegadesign** [comment]
Hi @oodesign 
Thank you for detailed information, but there is a problem with a logging, because when I click any plugin action, the Sketch crashes and closes itself, so there is no "Plugin Log.log" in ~/Library/Logs/com.bohemiancoding.sketch3/ folder as you described. Are there any other methods?

**Comment by oodesign** [comment]
Hi @vegadesign ,

May I ask you to disable all other plugins to discard any of them is getting in conflict with Merge Duplicates?
You can do so in the Sketch "Preferences > Plugins", or via the menu "Plugins > Manage plugins...", and unchecking the other plugins.

Is Settings (and other options) working fine by doing so? Or does the issue persist?

**Comment by vegadesign** [comment]
Done, but it does not work. When there is only one "Merge Duplicates" plugin, the Sketch crashes after clicking on any action

**Comment by oodesign** [comment]
Hi @vegadesign ,

We completely missed the "on M1 chip" part. I apologize for the inconvenience.

Merge Duplicates is not ready yet to work on M1 devices (per se), but please continue reading :) .

Merge Duplicates is based, as many other plugins, on [skpm with webview](https://github.com/skpm/sketch-module-web-view), but I'm afraid it's not ready yet to work properly on M1 devices (you may see many plugins fail because of this on M1s). Good news is that the creators (along with Sketch) are on it. As soon as we're able to release a fix for this issue I'll be happy to let you know.

Meanwhile, **you can run Sketch with the "Open using Rosetta" setting on**, and Merge Duplicates will work fine again. You can do so by:

1. Right click on the Sketch program from Finder, and tap "Get info" 
2. Select the checkbox that says "Open using Rosetta". The checkbox will stay active on subsequent launches until you manually uncheck it.
3. Open Sketch, and run Merge Duplicates as usual.

This workaround may also cause reduced performance in Sketch, since Rosetta is an app that enables Intel-based apps to run on Apple Silicon Macs. So I'd suggest to keep it on only when needed (while merging, in this case), and turn it off when going to regular design work again.

We know this isn't an ideal solution, and we're sorry for the inconvenience, but we hope it helps a bit in the meantime.

Also, please let us know how it worked for you, or any further issues you may find.

Thanks!

**Comment by vegadesign** [comment]
Hi @oodesign 

Thank you for the workaround! It works well. It should be said that there are no problems with Sketch performance.
The current issue can be closed

Thanks!
