### ISSUE TITLE
Merge layer styles of library

### ISSUE THREAD

**Issue by IrisvdLooij** [oodesign/merge-duplicate-symbols#141]
Dear support, 

On your website, you wrote under 'merge layer styles': 'including external libraries styles', but I can't make it work. This is my case:

I have 1 library called 'styles' with fills. 
Here I have testcolor 1 and testcolor 2, which have the same hex-code but different style names. 
I want to merge these. 

If I merge these styles in the library file, the instances in the connected sketch files still use the different styles testcolor 1 and testcolor 2. They are not merged. 
If I merge the styles in the connected sketch file, the original styles are both still present in the library file and therefor not merged for all other connected files to that library. 

I am looking for a way to merge these 2 styles, and that in all the connected sketch files (which are a lot of different ones) I only see the 1 leftover style as applied from that library. 
Can you help me? What am i doing wrong? 

<img width="497" alt="Schermafbeelding 2021-01-29 om 14 40 01" src="https://user-images.githubusercontent.com/71273987/106282420-d8d1f700-6240-11eb-9405-1641e6bee941.png">

**Comment by oodesign** [comment]
Hi @IrisvdLooij ,

I'm afraid Merge Duplicates action scope is restricted to the current open document, and therefore all "child" documents (files using library symbols or styles you are merging in the library file) won't get automatically updated.

A while ago it wasn't possible (due to Sketch restrictions) to get access to other documents to update them. Currently, Sketch enables plugins to update any "open document", so we may have an open door on that side (something like "merge these symbols/styles, and also update my other open documents", but it'd still need you to open the related documents). We're currently analyzing it, and I'll make sure to let you know if we're able to support it in the near future.

As a workaround (for now), I'd suggest to:

0. Say you have styles A and B in the library, and you just want to keep style A.

1. Open first the child document (not the library), and use "Merge layer styles (from list)". 
2. Select the styles that you'd like to merge (A and B). Choose the one you want to keep (A), and press Merge. This will update all the layers (and overrides) using the style you discarded (B), and apply style A to them. 
3. At this point, all related layers (in this child document) will be using style A (and none will be using B).
4. Now, open the library, and merge styles A and B.
5. At this point style B won't exist anymore in the library, and won't be used in the child document. So, hopefully that would be it.

We know this is not ideal, and if you have a bunch of child documents, updating first all of them may take a lot of time. 
I'll be happy to let you know if we're able to support multiple documents update it in the near future.

Hope this helps a bit!
