### ISSUE TITLE
Terms of sale

### ISSUE THREAD

**Issue by ColinLondon** [oodesign/merge-duplicate-symbols#142]
I was directed here by the Support link on your website.

Your website has no terms and conditions, so a couple of questions...

Is there a refund policy?

Is the licence fee per single computer, or can I use it on the multiple Macs I have?

TNX

**Comment by oodesign** [comment]
Hi @ColinLondon ,

Thanks for considering Merge Duplicates. We feel flattered!

Merge Duplicates is available under one of the following licenses:

- **[Single license](https://gum.co/mergeduplicatesymbols?variant=Single%20license)**: a single license to activate the plugin on a single device (yup, just one device).
- **[2 devices](https://gum.co/mergeduplicatesymbols?variant=2%20Devices) (🤩    New!)**: a license that may be used to activate the plugin on up to 2 devices.
- **[Team license](https://gum.co/mergeduplicatesymbols?variant=Team%20license)**: a shared license for the team, that you can use to activate the plugin on as many devices as you want (in your team).

If you just need it on one computer, **Single license** is the one for you. If you have a couple of devices (personal and work maybe?) I'd suggest **2 Devices**. And if you are in a team and are planning to use it on 4+ (four or more) devices, **Team license** is a better deal.

The refund policy is quite simple. If for whatever reason you're not happy with Merge Duplicates, just [let us know](mailto:licensing@oodesign.me) and we'll be happy to refund you the full amount of your purchase. We'd love to know about what didn't work well for you, so if you feel like it, we'd appreciate some feedback. But otherwise is also fine, no worries 😊.

After we've request your refund, you should receive an email confirming the refund, and receive the funds within 5-7 business days (as per Gumroad refund policy).

You may also find here the [Merge Duplicates EULA](http://mergeduplicates.com/docs/EULA.pdf) (End User License Agreement).

And... you're totally right! We should have these details in our site. I'll make sure to add it to our backlog.

Hope this helps a bit, but also please let me know any further questions or doubts you may have.

All the best,

Òscar from oodesign

**Comment by ColinLondon** [comment]
Thanks for the quick and detailed response, Oscar. Great plugin (I've been using it since the early days). To be honest, it is a bit pricey. Maybe run regular coupon campaigns or something to drive adoption. CIn cin

**Comment by oodesign** [comment]
Hi @ColinLondon ,

I completely understand. A while ago we wrote a letter about [why Merge Duplicates became non-free](https://medium.com/@ootomir/merge-duplicates-is-going-non-free-1faa211edab), and the reasoning below the pricing. Hope it helps somehow.

We don't use to do coupon campaigns, but we're always happy to support designers for who, for some reason, Merge Duplicates is too expensive (or out of reach), like students, low resources, starting a design career, or, for instance, living in a country where the salary conditions, economic power, or the currency conversion don't help at all.

If you feel like it may be your case, please [send us an email](licensing@oodesign.me), and we'll be happy to consider your case 😊.
