### ISSUE TITLE
Can I cancel my existing payment and pay with a different card?

### ISSUE THREAD

**Issue by hahohi** [oodesign/merge-duplicate-symbols#153]
Hello.
I have purchased and used the plugin, but for personal reasons I have to cancel my existing payment.
However, you still need this plugin. So I will pay again with a different card to purchase.
I know this is not common. But if you can help me, please answer me.

This plugin was purchased on May 8th.

**Comment by oodesign** [comment]
Hi @hahohi ,

We're trying to keep this space for technical issues related with the plugin itself.

Could you please [send us an e-mail](licensing@oodesign.me) with your current license key (or the e-mail account you used to complete the purchase), so that we can continue the conversation there?

Thank you! 😊

**Comment by hahohi** [comment]
Hi.
Thanks for the answer.

I sent the license key to the email below.
licensing@oodesign.me

**Comment by hahohi** [comment]
The answer was sent a few days ago. Please let me know what's going on.
