### ISSUE TITLE
Sidebar in dialog window cannot be enlarged – Long layer names cannot be read completely in this way 

### ISSUE THREAD

**Issue by sgxwrk** [oodesign/merge-duplicate-symbols#159]
**Problem:**
Unfortunately it is currently not possible to enlarge the left sidebar in the dialog window, so that longer layer names can be displayed fully.

**Improvement:**
The user can enlarge the sidebar with a mouse click to the right in order to be able to display longer layer names in full. (see red arrows in the screenshot). 

<img width="1312" alt="Bildschirmfoto 2021-06-12 um 22 11 41" src="https://user-images.githubusercontent.com/72497020/121788414-6e0cd100-cbcd-11eb-976e-f23b92edbdc0.png">

**Comment by oodesign** [comment]
Hi @sgxwrk ,

Thanks for reaching out! We're aware of this (and working on it). Hope to have a fix soon! 
There is already an [active issue](https://github.com/oodesign/merge-duplicate-symbols/issues/155) about this very same topic. 

I'm closing this one, so that we can follow and focus the conversation there, but if for some reason you feel this is different (or has some extra detail), please feel free to reopen it, or to add new content to the other issue.

Thanks!
