### ISSUE TITLE
Merge duplicate color variables not working

### ISSUE THREAD

**Issue by mxdslien** [oodesign/merge-duplicate-symbols#160]
Hi @oodesign!
I love the plugin, but I'm having some issues with color variables.
I've tried all the options (duplicate, similar and from list) and it fails the same way with every option. When I click the "Merge color variables" button after I've selected which color variables I want to merge, I get a swift beach ball loading spinner, then it goes back to the plugin window, as If I never clicked the "Merge color variables" button. 

I tried to create a new file, where merging works flawlessly. I also tried duplicating the current file I'm struggling with and deleting one page at a time until merging works, but it doesn't seem to be an issue with a specific page. It's really hard to pinpoint where the issue lies - maybe you have similar experiences? Is my file too big, or does the merge duplicate color variables have issues with specific stuff?

OS: macOS Big Sur 11.4
Merge duplicate 8.3.5

_I can't share the file as it's considered sensitive information (Job policy)_

**Comment by oodesign** [comment]
Hi @mxdslien ,

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge color variables - any of its variants - )
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and relaunch the app).
6. Logs will be stored by this point. May you please [send us](mailto:support@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by mxdslien** [comment]
Thank you! 
I have sent an email with the logs.

**Comment by oodesign** [comment]
Hi @mxdslien ,

Thanks for sending us the logs. They really do help!

We see there are some layers (or layer styles) in the file that are using the "TietoEVRY/01_Main" color variable, and for some reason their internal definition (in the Sketch file) has gone corrupt, and it's causing the plugin to fail when trying to update them.

Would it be possible for you (if sharing the original file is not an option) to prepare a separate file with all layers that may be using that variable, and try to run Merge Color Variables again? If it still fails, please [send us](mailto:support@oodesign.me) this separate file and we'll be happy to investigate further, and hopefully provide a fix for it.

Thank you!

**Comment by mxdslien** [comment]
Hi again! Thanks for the quick replies and with good instructions.
I feel like I've tried everything to no avail, and unfortunately, I haven't
been able to single out a specific element that causes the issue. Since
last time, I did notice that merging actually partially works. If I select
two color variables of different colors, all colors go to the variable I
choose to keep, but it does not delete the other variable (if that makes
any sense). While this is somehow useful, the way we work makes it
substantially more useful to actually delete the color variables we don't
want, to avoid getting additional options in the color list when choosing
what variable to use.
I have attached a file that also has the same issue.
Thanks a ton for your help so far. I don't know how many hours deep I would
be maintaining all files without the merge duplicate plugin - it's easily
the most useful plugin I have installed, so again, THANK YOU!!


tor. 17. jun. 2021 kl. 11:52 skrev Oscar Oto ***@***.***>:

**Comment by oodesign** [comment]
Hi @mxdslien ,

I'm afraid GitHub doesn't include the attached files when the reply is sent via mail.
Could you please upload them manually to this issue? Or just [send us](mailto:support@oodesign.me) the file, as you prefer :)

Thank you!

**Comment by oodesign** [comment]
Hi @mxdslien ,

Thanks a lot for sending us the file, and for your collaboration 🥰 .

Looks like we had an issue that could cause the plugin to fail when dealing with slices in the document,
We just released [v8.3.6](https://github.com/oodesign/merge-duplicate-symbols/releases/tag/v8.3.6), that hopefully fixes this issue.

Could you please give it a try and let us know how it worked for you?

Thanks!

**Comment by mxdslien** [comment]
Amazing!!
