### ISSUE TITLE
Popup not showing since Sketch for Teams

### ISSUE THREAD

**Issue by IrisvdLooij** [oodesign/merge-duplicate-symbols#161]
Since we started using Sketch for Teams, the merge duplicates popup for selected symbols is not or only sometimes showing. Sketch will start showing the loading animation, and eventually that will stop but nothing else happens. Is this fixable?

**Comment by oodesign** [comment]
Hi @IrisvdLooij ,

Sorry to hear that :(  

Are you experiencing this issue with all documents? Or just on some specific ones? If so, could you [send us](mailto:support@oodesign.me) a copy of the document so that we can test it on our end? It can be a reduced version of it (you may remove ~everything - artboards, styles, ... - as long as you can still reproduce the issue with it).

Also, to investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge color variables - any of its variants - )
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and relaunch the app).
6. Logs will be stored by this point. May you please [send us](mailto:support@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰
