### ISSUE TITLE
Licence switch

### ISSUE THREAD

**Issue by libertyink** [oodesign/merge-duplicate-symbols#163]
Hi! I want to switch my license to another device. How can I do it?

**Comment by oodesign** [comment]
Hi @libertyink ,

We're trying to keep this space for technical issues related with the plugin.
For licensing issues, may you please [send us an e-mail](mailto:licensing@oodesign.me) with your license key (or the e-mail account you used to acquire your license on Gumroad), so that we can continue the conversation from there?

Thank you!
