### ISSUE TITLE
sketch crashed

### ISSUE THREAD

**Issue by Windinapril** [oodesign/merge-duplicate-symbols#177]
Crashing with plug-in software
sketch版本91 (150837)
macOS Monterey 12.5.1 (21G83)

**Comment by oodesign** [comment]
Hi @Windinapril ,

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge color variables - any of its variants - )
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and relaunch the app).
6. Logs will be stored by this point. May you please [send us](mailto:support@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰
