### ISSUE TITLE
I need my license transferred to a new laptop

### ISSUE THREAD

**Issue by jteplow** [oodesign/merge-duplicate-symbols#188]
You have no way of contacting anyone to make this happen. What is next? I'd like to use merge duplicate for sketch. Thx

**Comment by oodesign** [comment]
Hi @jteplow ,

We're trying to keep this space for technical issues related with the plugin.
For licensing issues, may you please [send us an e-mail](mailto:licensing@oodesign.me) with your license key (or the e-mail account you used to acquire your license on Gumroad), so that we can continue the conversation from there?

Thank you!

**Comment by jteplow** [comment]
I have written to the license email and have not gotten any response

**Comment by oodesign** [comment]
Hi @jteplow ,

Our apologies! Somehow we missed your first email 🙈.
A response should be in its way by now.

**Comment by oodesign** [comment]
Hi!

I believe we addressed this issue via mail, so I'm closing this issue, but please feel free to reopen it otherwise.

Thanks!
