### ISSUE TITLE
The key cannot be used

### ISSUE THREAD

**Issue by BoneJour** [oodesign/merge-duplicate-symbols#189]
Hello, I purchased the key of the plug-in today, but after I input the key, it is displayed: "Looks like the license key is not valid.May you try again?" I have tried to use it many times, but still failed. Would you like to know how to solve it？ @oodesign

**Comment by oodesign** [comment]
Hi @BoneJour ,

We're trying to keep this space for technical issues related with the plugin.
For licensing issues, may you please [send us an e-mail](mailto:licensing@oodesign.me) with your license key (or the e-mail account you used to acquire your license on Gumroad), so that we can continue the conversation from there?

Thank you!

**Comment by BoneJour** [comment]
Ok, I have contacted you by email and sent the secret key to you. Thank you for your trouble

**Comment by BoneJour** [comment]
Hello, I still haven't received your email, could you please help to deal with it? It is urgent to use, thank you! @ @oodesign

**Comment by oodesign** [comment]
Hi!

I believe we addressed this issue via mail, so I'm closing this issue, but please feel free to reopen it otherwise.

Thanks!
