### ISSUE TITLE
Transfer license

### ISSUE THREAD

**Issue by kao264918** [oodesign/merge-duplicate-symbols#193]
Hello,

I have sent several emails to [licensing@oodesign.me](mailto:licensing@oodesign.me) almost a month ago, but I have not received any response so far. Therefore, I am reaching out here for assistance. I reinstalled my Sketch, which caused the license to consider it as a new computer. I would like to transfer my license.

Please check your inbox and help me with the license transfer issue. Thank you.

**Comment by oodesign** [comment]
Hi @kao264918 ,

I believe this issue is being addressed by mail now, so I'm closing this issue, but please feel free to reopen otherwise.

Thank you!

**Comment by kao264918** [comment]
@oodesign 
Hi, sorry ,I still have not got any response for my issue, nor does mail. Please help me solve this issue.

**Comment by oodesign** [comment]
Hi @kao264918 ,

Oh, that's unexpected! 
We reached out back on June 19th, but apparently you didn't receive that reply...
I just had the reply sent again to your email address. Could you please confirm if you receive it this time?
Otherwise, could you send us an email with an alternative email address we can reach you at?

Thanks!
