### ISSUE TITLE
Unable to merge duplicate symbols in Sketch version 49.2

### ISSUE THREAD

**Issue by zero-down** [oodesign/merge-duplicate-symbols#21]
After updating to Sketch 49.2 unable to merge duplicate symbols.

**Comment by oodesign** [comment]
Hi Travis!

We're not experiencing any issue with Sketch 49.2 ...

May we have any more clues about your design file, such as if it's working with symbols from other Libraries?

Would it be possible to have a copy (or a simplified version, with just the symbols but no real content) of the Sketch file so that we can dig a bit deeper and test it on our own?

Thanks!

**Comment by zero-down** [comment]
SOrry for the delay.

I've been testing this to find out what exactly is happening. I have an icon symbol within another symbol. For some reason its causing the Merge Duplicate to not run.

I uploaded the Sketch file and a video capture of the bug.

Sketch File:
https://www.dropbox.com/s/xc3y8kmglrfxu05/merge_duplicate_bug.sketch?dl=0

Video:
https://www.dropbox.com/s/j1ojzm7f7vde1bp/merge_duplicate_bug.mp4?dl=0

Take care!

**Comment by zero-down** [comment]
After more testing I'm almost positive that when the a symbol is embedded in another symbol it has to be embedded in its default state–otherwise it doesn't run. I was using "@color/dark, @color/light" as a layer being masked by the icon. I then placed the icon within another object and changed its color. I then turned that into a symbol.

**Comment by oodesign** [comment]
Hi Travis!

I'm not able to reproduce the issue with the attached file (it works from the first try, and I'm able to merge symbols).

It's a bit strange, because the plugin just uses the symbols name, no matter what they have inside.

Does it show any message the first time you try to run the plugin?
Which version of the plugin are you using?

**Comment by zero-down** [comment]
Hi,

Yeah. I thought I had figured it out, but I don't think I did. The only other thing I can think it could be is a conflict with another plugin–I have a lot of installed plugins.

I'm using Merge duplicate symbols 3.0.4
Sketch 49.3

**Comment by nickostyle** [comment]
Sorry for the off topic, but in 48.2 the plugin doesn't work, not even a window with duplicated symbols is shown, nothing is happen when I chose a plugin from menu. Reinstalled sketch, reinstalled everything.

**Comment by qmolee** [comment]
same issue on sketch 49.3

**Comment by oodesign** [comment]
Hi !

We're not experiencing any issue with Sketch 49.2, and neither on 49.3...

Would it be possible to have a copy (or a simplified version, with just the symbols but no real content) of the Sketch file so that we can dig a bit deeper and test it on our own?

Thanks!

**Comment by tomaszrybak** [comment]
Hi guys :)
In my case the problem was caused by a plug-in Diya. Uncheck this plugin and restart a Skech.

**Comment by oodesign** [comment]
Hi Tomasz! Thanks for the info!
We'll make some tests on our end and let you know.

Any of you (@qmolee , @zero-down , @nickostyle ) is using the Diya plugin?

**Comment by oodesign** [comment]
Hi!

We just released version 3.0.6, that hopefully would solve some of the issues causing the plugin to do nothing apparently in several situations.

Please, let us know if it did work for you!

Thanks @tomaszrybak ! The thing with the Diya plugin gave us some clues about what was wrong!
