### ISSUE TITLE
Nothing happens 

### ISSUE THREAD

**Issue by ashtothedust** [oodesign/merge-duplicate-symbols#25]
Hi, when I click on the 'merge duplicate symbols' from the plugin menu, nothing happens. Does this plug-in require a specific sketch version? I'm on v.48.2 and can't update due to the company system set-up. Please let me know. Thanks.

**Comment by oodesign** [comment]
Hi!

Sad to hear you're having issues with the plugin!

May we have any more clues about your design file, such as if it's working with symbols from other Libraries?

Would it be possible to have a copy (or a simplified version, with just the symbols but no real content) of the Sketch file so that we can dig a bit deeper and test it on our own?

Thanks!
