### ISSUE TITLE
Keep shared style override for merged symbols instances. 

### ISSUE THREAD

**Issue by imgrby** [oodesign/merge-duplicate-symbols#33]
I have icons in 3 colors since times when overrides of shared styles where not there yet. 
Now that we have it - I tried to merge 3 icons (symbol structure and naming is the same) but all instances had they shared style override switched to the style of merged symbol. 
E. g. I had blue, black and grey icon (all 3 using shared styles for a single vector shape). After merging I had 1 symbol with blue color and instances that had grey or black shared style also became blue. 
I think it may help people to improve library of long going projects if it's possible.

**Comment by imgrby** [comment]
[icons-merge.zip](https://github.com/oodesign/merge-duplicate-symbols/files/2662020/icons-merge.zip)
here you go

**Comment by oodesign** [comment]
Thank you! 

Just to make sure I got you well:

You have 3 Facebook logo symbols (blue, gray, and black). All "blue", "gray", and "black" are Layer Styles that are applied to those shapes (not Fill color).

In your design you have several instances of each of those symbols, depending on which color you needed in each place.

You'd like to merge those 3 Facebook logo symbols and have just one that you can use everywhere using the new "Color style override" feature, but you'd like to keep its color.

Is it right?

If that's the case, I assume that all of the symbol instances do not have a style override... so your problem is not about keeping style overrides. It's about "override the instance layer style with the  original symbol layer style". It's a bizarre sentence, but... does it make sense for you?

Then maybe the approach would be having a plugin option to "Merge duplicate symbols but keeping their original layer style"?

Thanks!

**Comment by oodesign** [comment]
Yes, that should work...
The "manual process" would be something like: 

1. Find all instances of the blue flacebook symbol (the "Find Symbol instances" plugin would be helpful here)
2. Set specifically their Layer style override to the "Blue layer style"
3. Replace all the symbol instances for the "black facebook symbol" (Sketch will keep the blue override, so they will keep blue).
4. Delete the Blue facebook symbol
5. [and do the same for the other color symbols...]

It's a bit tedious, but I guess it should work. Let me know if it does!

Anyway, I'll make sure to track interest on the "Merge duplicate symbols but keeping their original layer style" feature, as it still sounds interesting. I'll let you know if we move forward this feature.

Thank you!
