### ISSUE TITLE
Thank you for your work

### ISSUE THREAD

**Issue by Maikenvv** [oodesign/merge-duplicate-symbols#39]
Since I probably won't move to the paid plugin, I want to thank you for all the work you've done on this plugin in the past. I have loved using it.

**Comment by oodesign** [comment]
Hi @Maikenvv,

I'm happy that it was useful for you!
May I ask what prevents you from getting it?

Thanks a lot for your feedback! It means lot!

**Comment by nazohana** [comment]
Same here for our studio, we loved this plugin but we can't pay this plugin for each sketch version in all our computers. For the last weeks we were thinking to move to other apps like XD or Invision Studio, now with this paid version and the "runner" in the same way... we are seeing all benefits to moving. We appreciate all your work,  thanks for all.

**Comment by oodesign** [comment]
Hi @nazohana,

Sorry to hear that, but happy that it's been so useful for you.
Let us know how walking that path goes! 

Thanks for your support and feedback!

**Comment by varunyellina** [comment]
Hi @oodesign 

Thank you for building a great plugin which solved a problem faced by many of us working in teams. I congratulate you on your plans with making this a paid plugin so that you are compensated for your work. 👏

Unfortunately, the problem this plugin solves is a design issue for Sketch. I foresee Sketch fixing this at a later release(they raised funding recently). This plugin would be rendered useless and doesn't warrant a separate license. As @nazohana pointed out, we are looking to move to other tools(Figma) where we avoid this issue in the first place. I hope you get the drift.

Cheers

**Comment by oodesign** [comment]
Hi @varunyellina,

Honestly, we couldn't be happier if Sketch solved this issue natively. Merge Duplicates has always been (and will be) a "workaround" to the way Sketch handles this. 

That said, our personal guess is that this is not considered an issue, but a feature in Sketch. We think (and that's a personal point of view) that it's intentionally (per design) working this way, so that you can have styles and symbols with same names, and it's up to the designers to decide and handle what to do with them. 

We're just trying to make that decisions simpler and reduce countless hours of super boring manual work :)

And yes, you should definitely try Figma anyway! We're still with Sketch, but always keeping an eye on it.

Thanks for your support and feedback!

**Comment by Maikenvv** [comment]
> Hi @Maikenvv,
> 
> I'm happy that it was useful for you!
> May I ask what prevents you from getting it?
> 
> Thanks a lot for your feedback! It means lot!

I agree with some of the things the other have said. The price, which is 1/3, of the Sketch price, is quite expensive when there are multiple designers that use it. And as @nazohana pointed out, with more plugins being paid and the issue only being an issue in Sketch, moving to Figma is a serious consideration.

**Comment by oodesign** [comment]
Hi @Maikenvv,

We are enormously thankful for every designer using "Merge Duplicates", and the help and feedback you've been kindly giving us.

So when we decided to go non-free we thought of including a big discount on it if you are currently using the plugin, and get it before the 1st of June. It was our way to say Thank you, and make things a bit easier for all of you that have been helping us make it possible. 

Just trigger "Merge duplicates" in Sketch. You may find the discount in the notify dialog that appears after merging. Hope it helps a bit!

Anyway, whether you get it or not, thank you all for your using it until now and for your support and feedback.

All the best,

Òscar from oodesign
