### ISSUE TITLE
Layer styles appear twice after I merged two of them.

### ISSUE THREAD

**Issue by ChristopheHoro** [oodesign/merge-duplicate-symbols#50]
I used the plugin in order to merge 2 similar layer styles.
It seemed to work fine but now for some reason my layer styles appear twice in the dropdown menu: 
<img width="245" alt="Capture d’écran 2019-06-18 à 18 15 40" src="https://user-images.githubusercontent.com/44064450/59701578-380eff00-91f6-11e9-8ab1-d5b8a70ad9d1.png">

Is it a bug?

Thanks,

**Comment by oodesign** [comment]
Hi @ChristopheHoro ,

Sketch does present two lists in that panel. First is a collection of the recently used styles (which may be your document styles or styles belonging to the most recently used external library), and the other is the document styles.

May it be that what you are seeing are actually this two sets of styles, and that they match (because the recent ones are the ones in the document)?

You can also check all of your document styles in the Layer menu option, on "Layer > Organize Styles". In that list are you also seeing duplicate styles? Or just one of each?

Thanks!

**Comment by ChristopheHoro** [comment]
Your're totally right.
I'm still discovering how some stuff work in Sketch.
Thank you for your reply, that's not a bug at all :)

**Comment by oodesign** [comment]
Don't even worry! The checkmark of the "style in use" was the clue.
We've all been there, staring at those two lists and thinking... why are there two lists presenting the same items? Did I broke anything? 😅

Glad to help!
