### ISSUE TITLE
Merged symbols turn into a Red "x" box on all of my artboard

### ISSUE THREAD

**Issue by andrea-apollo** [oodesign/merge-duplicate-symbols#55]
Hi, not really sure what is happening or what these red boxes mean on my file. I merged multiple copies of our navbar and they seem to have disappeared and replaced with a red box with a red dotted outline and a circle with a line through it in the middle. Not really sure what's happening or how to fix it. Thanks.

![image](https://user-images.githubusercontent.com/43589988/61496569-6c9ae580-a971-11e9-89f1-0fbab9192b4d.png)

**Comment by oodesign** [comment]
Hi @andrea-apollo !

There are some things that may help us figure out what happened:

- Were those symbols in an external library, and is this design file referring to them? 
- Did you run Merge Duplicates on the design file, or on the external library?

Merge duplicate symbols merges symbols in the scope of a Sketch document. If this document is a library it will work fine, but it won't automatically update all of the other Sketch files that are using those symbols, and you'll need to replace them manually. When Sketch is not able to find the "master" symbol you'll be shown this red dotted shape.

Otherwise, may you please send us the design files to oscar@oodesign.me so that we can investigate further?

Thank you!
