### ISSUE TITLE
Plugin not working in 50.2

### ISSUE THREAD

**Issue by highvoltaged** [oodesign/merge-duplicate-symbols#56]
Plugin not working in 50.2
I know its an old sketch version, but im stuck with it cause i use Paddy.

Where can i download old versions?

Thanks

**Comment by oodesign** [comment]
Hi @highvoltaged ,

Which version of Merge Duplicates are you using?

Thanks!

**Comment by highvoltaged** [comment]
Hi,
4.0.11
I press Maybe later, and then nothing happens.

**Comment by oodesign** [comment]
Hi @highvoltaged ,

On May 2019 Merge Duplicates became a non-free plugin (you may [find here why](http://bit.ly/mergeduplicatesisgoingnonfree)). Since then we added the ability to [Merge Duplicate Layer and Text Styles](http://bit.ly/mergeduplicatestyles) , and soon we'll be releasing the ability to Merge Similar Styles.

If you're still interested in it you may [find it on Gumroad](http://bit.ly/getmergeduplicatesymbols), or click on the "I want it!" button in the dialog that will appear when you launch the plugin in Sketch.

Thanks!
