### ISSUE TITLE
Merge duplicate error in sketch 56.2

### ISSUE THREAD

**Issue by krdesign** [oodesign/merge-duplicate-symbols#57]
In sketch 56.2 the latest version of plugin pay version 5.0.2 does not work
this is the log. thankyou

TypeError: null is not an object (evaluating 'context.plugin.urlForResourceNamed("icon.png").path')
    at ShowExpiredWindow (/Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/MergeDuplicateSymbols.sketchplugin/Contents/Sketch/MergeDuplicateSymbols.cocoascript:19:104)
    at MergeSelectedSymbols (/Users/stefanofois/Library/Application Support/com.bohemiancoding.sketch3/Plugins/MergeDuplicateSymbols.sketchplugin/Contents/Sketch/MergeDuplicateSymbols.cocoascript:69:22)

**Comment by oodesign** [comment]
Hi @krdesign ,

The attached error belongs to the deprecated version of the plugin, so I'd recommend downloading it again from Gumroad and install it again.

You can find the download link in the mail or receipt you got from Gumroad.
Anyway, if you go to http://gumroad.com/library (and log in with the account you used to purchase the plugin) you may find all your purchases there. Click on the "Merge duplicates" one and you will find a direct download button there.

What you'll get is a zipped file. Unzip it and double click on the .sketchplugin file to install it. 
If you had a previous version installed you will be prompted to replace it for the new version (v5.0.2) or keep the old one. Press **Replace** to install the new one. And... you're ready to go!

Otherwise you can click on "Manage plugins" inside Sketch, right click on the "Merge Duplicates" one and Uninstall it. Then install it again by double clicking on the .sketchplugin file you just downloaded from Gumroad.

And that should be it! Let me know if you have further issues with it, or if you have any feedback (or new ideas!) for Merge Duplicates :)

Please, let me know if it worked for you.

All the best,

Òscar from oodesign

**Comment by krdesign** [comment]
ok thank you!
