### ISSUE TITLE
Possible to revert

### ISSUE THREAD

**Issue by mattbingco** [oodesign/merge-duplicate-symbols#58]
Would be great to revert to last merged state. I mistakenly overwrote (had the same name, but different) a symbol I actually need.

**Comment by oodesign** [comment]
Hi @mattbingco ,

You can actually ⌘+Z to undo the merge (Sketch does a great job at Undo operations, even if they involve several actions). If you're merging several symbols in a row, hit "Continue later", and undo the last actions performed until you get your symbol back.

Otherwise, you can always use the Sketch "File > Revert To" option to get a previous version of the document, open it, copy the symbol you lost, and paste it in your current file.

Does this help?

**Comment by mattbingco** [comment]
Yes understood, however, the issue wasn't noticed for quite a while. So I had done a bunch of changes etc. But would be great – and I'm sure quite a task to actually build in the plug-in – to revert to the symbol library separate of the native sketch revert.

I ended up reverting to a previous version of the doc, so not a huge deal.

Anyways I think the lesson learned here is to make sure you're not overwriting something and to name your symbols properly!

Great plug-in!

**Comment by oodesign** [comment]
Hi @mattbingco ,

I see. We'll think about it and track interest on it. It's enormously complex, though, I must say... 
However, if we find a way to get to it I'll be happy to let you know! :)

All the best!
