### ISSUE TITLE
Duplicate Style Error

### ISSUE THREAD

**Issue by minhnlq94** [oodesign/merge-duplicate-symbols#61]
Sketch auto duplicate Layer Style, Text Style when I select a layer/symbol and "Command C" -> "Command V"

**Comment by oodesign** [comment]
Hi @minhnlq94 ,

Sketch may cause this when copy/pasting stuff from other files to the one you're working (it's importing their styles too, and some may overlap with your current ones). If this is the case, the "Merge text styles" option inside Merge Duplicates would be helpful to get rid of the "bad" ones and assign the "good" ones to those layers.

Otherwise... this shouldn't happen. May I ask you to attach a screen capture of the issue, or to describe it in more detail?

Thanks!
