### ISSUE TITLE
Merging symbols, detaches instances

### ISSUE THREAD

**Issue by kbsmth** [oodesign/merge-duplicate-symbols#64]
I have a library that has been going through a consolidation process, and attempted to use Merge Duplicate Symbols as a means of simplifying several of our duplicated components. The problem we have run into is that even though it behaves like it should in the local instances, it doesn't cascade into other files using those symbols. 

The instances of the symbols which were merged into the new "master" get detached from the symbol and turn into local symbols, rather than being attached to the updated master symbol. 

Our intended outcome of this process is that those instances would also inherit the link to the new master symbol, where the user would see a Library Updates Available notification to prompt them to accept the changes, and maintain connection to the library.

**Comment by oodesign** [comment]
Hi @kbsmth ,

Merge duplicate symbols merges symbols in the scope of a Sketch document. If this document is a library it will work fine, but it won't automatically update all of the other Sketch files that are using those symbols, and you'll need to replace them manually 😔.

Merging symbols (including external libraries) is the next big thing in our backlog. With it you may be able to merge symbols with your linked libraries, so that if you choose to keep the library one, the local symbol would get removed (kind of "syncing" with the library).

In your scenario the process would look something like:
1. Go file by file using, and run Merge Duplicates (including linked libraries)
2. Choose to use/keep the symbols coming from the library, and not the local ones
3. When you're done with all files, go to the Library and run Merge Duplicate Symbols to merge the duplicates and get rid of the "clones".
4. At this stage, all instances should be using the right library symbol, and your library should be clean of duplicates...

May that help?

Thanks!

**Comment by kbsmth** [comment]
@oodesign - In theory, yes that workflow is a solution we can provide to our library consuming designers as a means to an end. However, I am a little bit hesitant since our libraries are provided to 100+ designers, all of which have dozens of files linked to the libraries. 

I have learned from providing this type of instruction to a group this size in the past, that things are more often likely to break, than they are to fix everything. 😬

How long do you think it will be until Merge Duplicate Symbols supports this functionality?

**Comment by oodesign** [comment]
Hi @kbsmth ,

Completely understand, and fully agree. Any situation in which you need to "spread" a new symbol to all of your design files to replace the one that was used is just a headache in Sketch. Most of the solutions we can come up with (even this one we're discussing with Merge Duplicates) seem only to be a workaround, and may lead to other issues or unnoticed design changes.

Just as an example. In your case, if designers have Symbols A1, B1, C1, and you want them to be replaced by a library symbol called A, you'd need to replace them all (or merge them) with symbol A, but as Sketch doesn't apply overrides based on layer name, but on an internalID ([can see more details here](https://github.com/oodesign/merge-duplicate-symbols/issues/63)), it's highly probable that all your overrides for A1, B1 and C1 will be lost.

I'm not sure if there is anything (from a plugin side) we can do about it. And it may get more complex with 3rd instances like Abstract, but we'll work on it. If we come up with a solution I'll be happy (really really happy) to let you know.

Oh, and Merge Duplicate Symbols (including libraries) is expected by November.

**Comment by kbsmth** [comment]
The A1, B1, C1 is exactly my scenario. One thing we have done in our library masters is to prevent style overrides within the symbols, so a user can essentially change the state of a component, or they can change the text, but we lockdown the style overrides. 

I'll be looking forward to the November release - hopefully that will solve some of our other issues.

**Comment by oodesign** [comment]
Hi @kbsmth ,

I'm really happy to announce a [brand new Merge Duplicates](https://youtu.be/HZLn2zQMMCI) 🥳, that you can already download straight from [Gumroad](https://gumroad.com/library) or from [GitHub](https://github.com/oodesign/merge-duplicate-symbols).

And to celebrate we arranged [this cool video](https://youtu.be/HZLn2zQMMCI) showing the new cool stuff. Don't miss it out!

It includes...

- Merge symbols from linked libraries ⭐️⭐️⭐️
- Whole brand new UI
- Merge all symbols from a single window
- List and Card view
- Updates back in native Sketch
- And many many more...

Hope you like it! And happy merging!
