### ISSUE TITLE
Purchase via Paypal failed

### ISSUE THREAD

**Issue by randyrec** [oodesign/merge-duplicate-symbols#70]
I just purchased using the paypal option. I have the receipt from paypal but the gumroad website threw an error and wouldn't proceed.

Who can I contact with the details?

**Comment by oodesign** [comment]
Hi @randyrec ,

We're trying to keep this space just for technical issues related with the plugin.
May I ask you to send me an e-mail to oscar@oodesign.me (with some details like the e-mail account you used for the purchase) so that we can continue the conversation there?

Thank you! 😉

Òscar from oodesign

**Comment by randyrec** [comment]
Thank you! I couldn't find your email. I will send a note.
