### ISSUE TITLE
Reactiving Paid plugin

### ISSUE THREAD

**Issue by aggie-for** [oodesign/merge-duplicate-symbols#71]
Had to reset my MacBook, and reinstall sketch, now I can't relink paid version. The only thing I have is email invoice. Can anyone help me?

**Comment by oodesign** [comment]
Hi @aggie-for ,

We're trying to keep this space just for technical issues related with the plugin.
May I ask you to send me an e-mail to oscar@oodesign.me (with some details like the e-mail account you used for the purchase) so that we can continue the conversation there?

Thank you! 😉

Òscar from oodesign
