### ISSUE TITLE
Use plugin in another computer

### ISSUE THREAD

**Issue by TSHDesign** [oodesign/merge-duplicate-symbols#72]
I bought the Merge Duplicates plugin and already have my license key but need to use it in a new computer. How can I use my license in this new computer instead of my old one? Is it possible?

Thank you in advance

**Comment by oodesign** [comment]
Hi @TSHDesign  ,

We're trying to keep this space just for technical issues related with the plugin.
May I ask you to send me an e-mail to oscar@oodesign.me (with some details like the e-mail account you used for the purchase) so that we can continue the conversation there?

Thank you! 😉

Òscar from oodesign

**Comment by oodesign** [comment]
Solved offline 😉
