### ISSUE TITLE
Symbols overwriting not working properly

### ISSUE THREAD

**Issue by raquel518** [oodesign/merge-duplicate-symbols#73]
When clicking one symbol (e.g button), the father artboard inherits the label that was overwritten:

![ezgif-7-693c90ba5889](https://user-images.githubusercontent.com/61468082/75264228-06b7eb80-57e7-11ea-93cd-bd4fe74bfc8e.gif)

**Comment by oodesign** [comment]
Hi @raquel518 ,

Sorry to hear that. I'm afraid we're not able to reproduce the issue you describe with our testing set, though 🙈.

Which Sketch, MacOS and plugin version are you using? 

May you send us a Sketch file with just the symbols that are causing the issue so that we can dig a bit deeper?
You may replace its real content by dummy rectangles, if you wish to. We only need the layer styles and its names.

Or a screen capture with the whole process, where we can see:
- Having some symbols to merge
- Run the plugin and merge them
- Reproduce this label overwrite behavior

Thanks a lot!

**Comment by oodesign** [comment]
Hi @raquel518 ,

Does this issue continue to occur?
