### ISSUE TITLE
Merge duplicate text style Error

### ISSUE THREAD

**Issue by smart23033** [oodesign/merge-duplicate-symbols#74]
Hello from South Korea.
I have some error, and need to solve it ASAP.

Its pretty awesome, but Merge Duplicate TextStyle is not working.
I clicked everything about mergeTextStyle, but noting happened even if I have duplicate textStyle.

Please solve this problem. Thanks.

I have version 6.0.9, and sketch 63.1.

**Comment by oodesign** [comment]
Hi @smart23033 ,

Sorry to hear that! I'm afraid we're not able to reproduce the issue you describe with our testing set, though.

May I ask...

- Which MacOS version are you using? 
- Is it a standalone file (with local styles), or styles come from linked libraries?
- Does Merge Duplicate Text Styles work if you create a brand new file and copy your texts (and related text styles there)?
- And I know this is the toughest one, but by far the most useful one for us --> May you send us the Sketch file, or a brand new Sketch file with just the texts and styles that are causing the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need the text layers and related text styles.

Thanks!

**Comment by oodesign** [comment]
Hi @smart23033 ,

We found several things that may be related to your issue:

- May you check if you have all typefaces in the project installed? We use to have issues with non-available fonts (we're working on it), and could be the cause of some issues.

- We found a bug that caused Merge Duplicates to fail when texts had the original default color (usually black). Just to try if this is the issue, you may change manually the color of the text styles and run the plugin again. We published v6.0.10, that should fix this issue. Please let us know otherwise.

- Your text style names seem to have slightly different names. For instance, we can see "Roboto_80 / Left" (with spaces before and after the slash), and "Roboto_80/Left". In the Components panel seem to be exactly the same (because Sketch trims spaces), but renaming any of the two should fix the issue, and Merge Duplicate Text Styles will find them.

![Screenshot 2020-03-02 at 14 27 13](https://user-images.githubusercontent.com/11992834/75680489-0067ba80-5c92-11ea-9f27-899b5b2e1f96.png)

Please let us know how it worked for you :)

Thanks!

**Comment by smart23033** [comment]
Hello @oodesign

**Comment by oodesign** [comment]
Hi @smart23033 ,

Are you still having issues with Merge Text Styles?

**Comment by charlieathmx** [comment]
Can I use a copy of Merge Duplicates on more than one computer?

**Comment by oodesign** [comment]
Hi @charlieathmx ,

We'd love to offer licensing per user, but unfortunately, due to some platform restrictions, Merge Duplicates (as well as Sketch Styler) is licensed per device.

**Comment by smart23033** [comment]
Sorry to reply too late. 🙏

After you updated, problem solved!

Thank you for everything you made. Take care!

+
And, Can I ask for small thing?
Latest version's UI is very beautiful. but, I can't see my style or symbol's full name in left panel.
I wish I can resize panel size through drag or double click like MacOS finder do.

Thank you so much from Korea.

**Comment by oodesign** [comment]
Sure, that'd be great!

I'lll make sure to let you know when it makes it to a release :)

Thanks for your feedback!
