### ISSUE TITLE
Merge duplicates window doesnt open?

### ISSUE THREAD

**Issue by drewpreiner** [oodesign/merge-duplicate-symbols#77]
I was using the free trial and when I would select the plugin from the plug in menu the pop up menu would show asking me to start a free trial or buy it. When I hit free trial, nothing would happen. Thinking this was an error or bug in the trial software I purchased the product and now nothing happens when selecting the plug in from the menu. I am on Sketch 63.1 on a Mac running 10.14.6

**Comment by oodesign** [comment]
Hi @drewpreiner ,

I'm sorry you're having a bad experience with Merge Duplicates...

I'm afraid we're not able to reproduce the issue you describe with our testing set, though. May I ask you for some more details that could help us figure out what the issue may be? 

- Which plugin version are you using (latest is 6.0.10)?
- Which plugin command are you running? (Merge duplicate symbols, layer styles from list, similar text styles, ...)
- Is it a standalone file (with local symbols and styles),  or do you have symbols and styles coming from linked libraries (including Abstract ones)?
- If there are linked libraries, do those libraries appear as Active (checked) in your Sketch Preferences window?
- Does Merge Duplicates work if you create a brand new file create some dummy duplicate (with the same name) symbols or styles?
- If the previous one works, does Merge Duplicates work if you copy your real file symbols or styles onto the new file, and run the plugin again? 
- And I know this is the toughest one, but by far the most useful one for us --> May you send us a Sketch file, or a brand new Sketch file with just the symbols or styles that are causing the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need the symbols/styles.

Thanks a lot!

**Comment by drewpreiner** [comment]
Thanks for the quick response here!

1. 6.0.9. - I keep trying to install 6.0.10 and its not taking?
2. Looks like nothing is getting the modal to pop up except merge similar layer styles and merge selected symbols.
3. This is a library file, so it’s being used by the program itself, but I’m editing in the master file.
4. Nope. Merge duplicate layer styles from list is the one I’m needing to use, but not working in a brand new file either.

https://www.dropbox.com/s/reuetfvsfudripe/_Master_Style_Guide.sketch?dl=0

D

Drew Preiner / UX + Product Designer
612.849.9446 / drewpreiner.com
Click here to see my PDF Portfolio

**Comment by oodesign** [comment]
Hi @drewpreiner ,

Thanks a lot for all details and the Sketch file!

I'm afraid we still can't reproduce the issue you describe, though... not even with older versions of the plugin. So this are a few things I'd ask you to try out next:

1. We just updated the plugin to v6.0.13. Can you update and check if the issue persists? You should be able to update it directly from Sketch, so please try first there. Otherwise you can install it manually from [GitHub](https://github.com/oodesign/merge-duplicate-symbols/releases/tag/v6.0.13) (just download it, extract files, and double click on the .sketchplugin file).

2. If still doesn't work, may you try disabling all your other plugins for a moment and try to run Merge Duplicates? You can do so by going to Plugins > Manage plugins, and unchecking them all.

3. Can you check if you have missing fonts in your file (you may see a turquoise warning in Sketch top-right corner)? If so, does installing the fonts (or replacing them with the Sketch built-in tool) solve the issue?

4. May you check if you have disabled (or not able to locate) linked libraries in your Sketch preferences? Disabled ones appear as unchecked, while "not able to locate" do show a warning notification.

Thanks for trying all of this out. We apologize for all the inconvenience this is causing to you, and please be sure that we'll fully refund your purchase if we're not able to make it work for you.

Hope it helps!

**Comment by zaprice-clgx** [comment]
I am having this exact same issue... whenever I try to Merge Text Styles or Layer Styles I can tell something is running because the menu item Plugins remains highlighted for a couple of seconds but I never get the window to make any selections. I have tried this on my symbols page, other pages, with and without selecting artboards as well as selecting styles from the components window.

I just updated to 6.0.13, I wasn't even aware that this version was available as I purchased from you guys just a few days ago as was sent to download 6.0.9 from that purchase.

**Comment by oodesign** [comment]
Hi @zaprice-clgx ,

Thanks for reaching out! 

I'm afraid we release patch updates faster than we can update installers on Gumroad 😅. When Sketch is launched it checks automatically if there are available updates for any installed plugin and asks you to update accordingly (and we just relied on it), but... are you experiencing any issue with Merge Duplicates (or other plugin) not autoupdating?

Regarding the issue you describe, may I ask you for some further detail?

- Which plugin version are you using (latest is 6.0.13)?
- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window?
- If there are linked libraries, may you check if you have disabled (or not able to locate) linked libraries in your Sketch preferences? Disabled ones appear as unchecked, while "not able to locate" do show a warning notification.
- Does Merge Duplicates work if you create a brand new file create some dummy duplicate (with the same name) styles?
- If the previous one works, does Merge Duplicates work if you copy your real file symbols or styles onto the new file, and run the plugin again?
- If still doesn't work, may you try disabling all your other plugins for a moment and try to run Merge Duplicates? You can do so by going to Plugins > Manage plugins, and unchecking them all.
- Can you check if you have missing fonts in your file (you may see a turquoise warning in Sketch top-right corner)? If so, does installing the fonts (or replacing them with the Sketch built-in tool) solve the issue?

- And I know this is the toughest one, but by far the most useful one for us --> May you send us a Sketch file, or a brand new Sketch file with just the symbols or styles that are causing the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need a file in which the issue can be reproduced.


Thanks!

**Comment by oodesign** [comment]
Hi @drewpreiner !

Are you still having the same issues with v6.0.13?

Thanks!

**Comment by oodesign** [comment]
Hi @drewpreiner  and @zaprice-clgx ,

We just published v6.0.15. May you give it a try and let us know if you have the same issues as before?

Thanks!

**Comment by zaprice-clgx** [comment]
Hey @oodesign, 

Thanks for the info. I was writing up the details and I just saw this. Just as a FYI, 6.0.14 did show up as an available update within Sketch.  I'll update and check again, and thanks for being so responsive. I'll get back to you today.

**Comment by zaprice-clgx** [comment]
Hey @oodesign,

So I updated the plugin to v.6.0.15 and I can now get a window for all three merge options. The only problem that I am running into now is that when I got through a list of options to merge, and I select my choice for more than 2 different layer styles, it will crash Sketch. It crashed Sketch when I went through and chose a selection for over 40 as well.

It will merge when I only pick 1 or 2 styles to merge, however, the layer style doesn't remain visible in the Components panel after the merge is complete. The style is still in the file, but I have to go to a component using one of the disappeared styles and select the component before it reappears in the Components panel.

**Comment by oodesign** [comment]
Hi @zaprice-clgx ,

Thanks for your feedback! We'll investigate the issue you describe. I'll let you know as soon as we make any progress on this.

Thanks!

**Comment by pedromsduarte** [comment]
Hi @oodesign ,
just started using the plugin, v6.0.16, and the reason why was for merging text styles. Functionality that I can't use, because the popup window doesn't open and I can't select anything.
The components and layer style it opens the window do select the styles I want to merge.
Can you please help?
Thanks

**Comment by oodesign** [comment]
Hi @pedromsduarte ,

I moved this to a new issue, as the issue described in this thread has evolved to a slightly different topic/issue and we'd like to keep them separated. :)

Thanks!

**Comment by oodesign** [comment]
Hi @zaprice-clgx and @pedromsduarte ,

We just released Merge Duplicates v6.2.1 (the plugin should auto-update), which the ability to log the Merge Duplicates processing details.

Regarding your issue, I'd like to ask you to do the following:

1. Make sure you update to Merge Duplicates v6.2.1
2. Quit Sketch
3. Open Sketch again, and open the file you're having issues with
4. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
5. Run the Merge Duplicates command you were having issues with (I believe it was Merge Duplicate Text Styles and Merge Text Styles from list)
6. Proceed as usual until you experience the issue you described. Don't quit Sketch yet (this is important, as Sketch logs are deleted when you quit the app).
7. Logs will be stored by this point. May you please [send us your log file](mailto:oscar@oodesign) so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment]
Hi @zaprice-clgx and @pedromsduarte ,

We just released v6.2.2, which should hopefully fix the issue you described. May you please give it a try and let us know how it worked for you?

Thanks!

**Comment by zaprice-clgx** [comment]
@oodesign,

Thanks for the update on this issue. After having tested v6.2.1 I am no longer experiencing the issue. Great work man, and thank you for the help.

Zach

**Comment by oodesign** [comment]
Hi @zaprice-clgx ,

Happy to hear it's working back for you, Zach! It's awesome news!
Thanks a lot for testing it back and for your help! 🥰
