### ISSUE TITLE
Plug in not working

### ISSUE THREAD

**Issue by Myeche** [oodesign/merge-duplicate-symbols#89]
Hi, since I updated to the 6.3.0 and sketch 66.1 the plugin is not working anymore. I get the pop up window but nothing happens when I click on merge

**Comment by oodesign** [comment]
Hi @Myeche ,

Sorry to hear that!

May I ask you some further detail?

- Which MacOS version are you running?
- Are you having this issue with just one design file, or does it also occur on others, a blank new document, ...?
- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window? Does disabling them (uncheck them in the Libraries list in Sketch Preferences) help with the issue?

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. 

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. Don't quit Sketch yet (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by Myeche** [comment]
Hi @oodesign 
Thank you for your quick answer

- I run MacOS Catalina 10.15.5
- it seems to be affecting only one file 
-  I tried disabling libraries and reinstalling the plugin but it didn't work
I emailing you the log, let me know if I can give you more information
Thanks for your help

**Comment by oodesign** [comment]
Hi @Myeche ,

Thanks a lot for the details and for sending us the logs!

We just released v6.3.1, that may help fixing part of the issue you described. May you please update to this new version, and try to run the same plugin actions again?

We've also enhanced logs a little bit to get deeper detail when merging layer styles. I'd still ask you to keep the Merge Duplicates logs setting enabled and [send us back the new logs](mailto:oscar@oodesign.me) if it still doesn't work for you.

Again thanks a lot for your help! 😉

**Comment by Myeche** [comment]
It worked! Thank you so much

**Comment by oodesign** [comment]
Happy it worked for you! 

Please remember to turn off logs if not needed, as they may slow a bit the plugin processing.

Thank you for everything! Couldn't have made it without your help! 🥰
