### ISSUE TITLE
Looking for duplicates never ends

### ISSUE THREAD

**Issue by therealdimitry** [oodesign/merge-duplicate-symbols#90]
I am trying to merge duplicates in a sketch file which I am using as a library via abstract. It has 151 symbols. Each time i try to run Merge Duplicates, it cannot get past the Looking for duplicates page. Have been waiting for 20+min.

**Comment by oodesign** [comment]
Hi @therealdimitry ,

Sorry to hear that! 151 symbols shouldn't take long time to process (should be pretty fast, actually), so maybe there is an issue there.

May I ask you some further detail?

- Which MacOS version are you running?
- Are you having this issue with just one design file, or does it also occur on others, a blank new document, ...?
- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window? Does disabling them (uncheck them in the Libraries list in Sketch Preferences) help with the issue?

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. Don't quit Sketch yet (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us your log file](mailto:oscar@oodesign.me) so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log


Thanks a lot for your help! 🥰

**Comment by jamessimo** [comment]
+1 for the exact same issue. 

Sent my log via email. I noticed this at the end of the log.

`{ Error: An Obj-C exception occurred.
    at [native code] (/)
    at R (/Users/*/Library/Application Support/com.bohemiancoding.sketch3/Plugins/merge-duplicates.sketchplugin/Contents/Sketch/Main.js:1:17125)
    at GetSpecificSymbolData (/Users/*/Library/Application Support/com.bohemiancoding.sketch3/Plugins/merge-duplicates.sketchplugin/Contents/Sketch/Main.js:1:28189)
    at /Users/*/Library/Application Support/com.bohemiancoding.sketch3/Plugins/merge-duplicates.sketchplugin/Contents/Sketch/Main.js:1:44316
    at emit (/Applications/Sketch.app/Contents/Resources/core-modules/@skpm/events/index.js:146:17)
    at emit (/Users/*/Library/Application Support/com.bohemiancoding.sketch3/Plugins/merge-duplicates.sketchplugin/Contents/Sketch/Main.js:1:68236)
    at userContentController:didReceiveScriptMessage: (/Users/*/Library/Application Support/com.bohemiancoding.sketch3/Plugins/merge-duplicates.sketchplugin/Contents/Sketch/Main.js:1:67576)
    at /
  nativeException: <NSException> -[MSImmutableColor setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x600000306cb0 }
`

**Comment by oodesign** [comment]
Hi @jamessimo ,

We're aware of this issue, and currently working on a fix.

We've identified this issue on Sketch files using tint overrides. May it be your case? 
The exact pattern for the issue was:

- Having symbols with **Tints** defined. Let's say this is **SymbolA**.
- Having other symbols that had the initial symbol inside of them (symbol nesting). So that would be **SymbolB containing SymbolA**.
- In SymbolB, there was a **group containing SymbolA** (let's call it TintGroup), and the group **also had a tint defined** on it.
- In any artboard, SymbolB was used, and there was a **tint override set for the TintGroup** group.

Does any of that sound familiar to you? 

Thanks for your help!

**Comment by jamessimo** [comment]
I will run some tests to see. I do use tints on some symbols but not the ones I was testing with but can double check.

**Comment by jamessimo** [comment]
I ran a test as you said. 

Whiles, it did still worked it too a very long time to render, like x10 the time if it was merging non-nested-tint symbols.

I think the issue on my end is just nested symbols, looking at my logs the script seems to choke when managing nested symbols. 

When I get more time I will try to make more test using my production assets.

**Comment by oodesign** [comment]
Hi!

If you have been able to arrange a Sketch (or several) where you can reproduce this long processing time, could you please [share it with us](mailto:oscar@oodesign.me)?

Thanks!

**Comment by oodesign** [comment]
Hi @jamessimo @therealdimitry ,

We just release v6.5.0, which will hopefully solve this issue.
May you please check it out and let us know how it worked for you?

Thanks!

**Comment by jamessimo** [comment]
Can confirm my issue is closed, still super slow but it does find the duplicates. 

If I try to do too many at the same time it will crash sketch so I do it in batches of 3.

**Comment by oodesign** [comment]
Hi @jamessimo ,

Thanks a lot for your feedback!
We are actively working on getting better performance (also on Sketch side).

Hope we can release a better-performing version soon :)
