### ISSUE TITLE
Merge text styles from the list doesn't work

### ISSUE THREAD

**Issue by skynet01** [oodesign/merge-duplicate-symbols#99]
I am running Sketch 68. I have a file with multiple pages and this file has a library attached to it. The popup with text styles from both files comes up correctly and i am able to select the styles that i want to merge. When i hit "Merge styles" nothing happens. 

Am i doing anything wrong? Do i need to first select the layers?

**Comment by oodesign** [comment]
Hi @skynet01 ,

Sorry to hear that :(

May I ask you for some further detail?
- Which MacOS version, Sketch version, and MergeDuplicates version are you running?
- Are you having this issue with just one design file, or does it also occur on others, a blank new document, ...?
- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window? Does disabling them (uncheck them in the Libraries list in Sketch Preferences) help with the issue?

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. Don't quit Sketch yet (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please send us your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by skynet01** [comment]
Running Sketch 68 on Mac 10.15.6 here is the log file
[Plugin Log.log](https://github.com/oodesign/merge-duplicate-symbols/files/5132558/Plugin.Log.log)

- This behavior happens with a blank document that only has a single text style and i try to merge it with a style from a library file. 

- Other text merging functions like "...Same name" and "..similar styles" works correctly

**Comment by oodesign** [comment]
Hi @skynet01 ,

Thanks a lot for the details (it helped a lot!).

We can reproduce the issue you're describing, and are actively working on a fix for it.
I'll make sure to keep you updated.

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment]
Hi @skynet01 ,

We just released v6.4.2, that will hopefully solve the issue.
May you please give it a try, and let us know how it worked for you?

Thanks!

**Comment by skynet01** [comment]
Yey it works now! Thank you for quick fix! :)
- Would be awesome if the list mode contained a search filter to quickly find styles.
- Also, some progress bar would be nice. If you have large documents you just get a loading beachball for 10 minutes and hope that everything is ok.

**Comment by oodesign** [comment]
Hi @skynet01 ,

Glad it worked for you!
And thanks a ton for the feedback. We really appreciate! 🥰
